<?php

/**
 * File: Domain_registration module
 * Restricts registration to people whose email addresses are of a particular domain
 */

/**
 * Implements hook_menu
 */
function domain_registration_menu() {
  $items['admin/config/system/domain_register'] = array(
    'title' => t('Domain registration'),
    'description' => t('Set domains for registration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('domain_registration_admin_form'),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Administration form for domain registration
 */
function domain_registration_admin_form($form, &$form_state) {
  $form['domain_registration'] = array(
    '#type' => 'textarea',
    '#required' => TRUE,
    '#title' => t('Email domains'),
    '#default_value' => variable_get('domain_registration'),
    '#description' => t('Enter the domains you wish to restrict registration. One entry per line in the format (e.g. something.com)'),
  );
  $form['domain_registration_message'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Error message'),
    '#default_value' => variable_get('domain_registration_message', t('You are not allowed to register for this site.')),
    '#description' => t('Enter the error message you want the user to see if the email address does not validate.'),
  );
  return system_settings_form($form); 
}

/**
 * Implements hook_form_form_id_form_alter()
 */
function domain_registration_form_user_register_form_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][] = 'domain_registration_user_register_validate';
}

/**
 * Custom validation function
 * Checks if the domain in the email address is on a list of allowed domains
 */
function domain_registration_user_register_validate(&$form, &$form_state) {
  $mail = explode('@', $form_state['values']['mail']);
  $domains = variable_get('domain_registration', FALSE);
  $domains = explode("\r\n",$domains);
  if (!empty($domains)) {
    foreach ($domains as $domain) {
      if ($domain == $mail[1]) {
        return;
      }
    }
  }
  form_set_error('mail', variable_get('domain_registration_message', t('You are not allowed to register for an account on this site.')));
}